<?Php
require('fpdf.php');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: *');




class PdfEncode extends FPDF{
    
  
   function header()
   {
            $body = file_get_contents('php://input');
            $data = json_decode($body)->{'data'};

            $this->Image('icon.png',10,10,30,10);

            $this->SetFont('Courier','B',16);
		    $this->SetTextColor(0, 0, 0);
        
            $this->Ln(30);


            $this->Cell(0,0,"Bus Point Report",2,0,'C');
            $this->SetFont('Courier','B',12);
		    $this->SetTextColor(0, 0, 0);
        
            $this->Ln(30);

            $this->Cell(0,0,"This is a auto generated list for report with bus point system",2,0,'C');
            $this->Ln(6);
            $this->Cell(0,0,"These are requested student from the system" ,2,0,'C');
            $this->SetFont('Arial','B',13);

            $this->Ln(20);

            $this->SetTextColor(13, 71, 148);
            $x = $this->GetX();

            $this->Cell(10,6,'No.', 1,0);
            $this->Cell(50,6,'Firstname', 1,1);

            $this->Cell(50,6,'Lastname', 1,0);
            $this->Cell(50,6,'ID Number', 1,1);
            $this->Cell(50,6,'Email', 1,1);
            $this->Cell(50,6,'Student Number', 1,1);

            $this->SetTextColor(0, 0, 0);

            $this->SetFont('Arial','B',7);

        for($i = 0; $i < count($data); $i++)
        { 
            $this->SetX($x);
            $this->Cell(10,$data[$i]->id, 1,0);
            $this->Cell(50,6,$data[$i]->firstname, 1,1);
            $this->Cell(50,6,$data[$i]->lastname, 1,1);
            $this->Cell(50,6,$data[$i]->datetime, 1,1);
            $this->Cell(50,6,$data[$i]->activity, 1,1);
            $this->Cell(50,6,$data[$i]->studNum, 1,1);
        }

        

   
        
        $this->Cell(0,180,"This document was generated by the system of Bus Point for admin" ,2,0,'C');
        
       
   }
}


$printOut = new PdfEncode();
$printOut->AliasNbPages();
$printOut->AddPage('L','A4',0);
$printOut->Output("I","student-list-report.pdf");



?>